### ISSUE TITLE
Improve workflow run titles for better readability

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node-tests#1547]
We could probably improve workflow names on the list of jobs that were ran by adding some specific params to it e.g.
`Environment`, `TX_EXRA`, `CLUSTER_ERA` or whatever is applicable to that workflow:

![image](https://user-images.githubusercontent.com/2938515/208905017-a6b05fcf-64d9-4b44-a3b2-5e51372baad4.png)

As an example of what I am using to help me distinguish executions on different environments and with different parameters:

This can be achieved with `run-name`, example below:

```yaml
name: db-sync - full cycle tests
run-name: tests on ${{ github.event.inputs.environment }} | db - ${{ github.event.inputs.db_sync_branch }} | node - ${{ github.event.inputs.node_branch }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment on which to run the tests - shelley-qa, preview, preprod or mainnet
        required: true
        default: "preprod"
<rest skipped>
```

### Result

![image](https://user-images.githubusercontent.com/2938515/208905549-bd3e084b-a968-42a3-b73a-70c1a1acccf2.png)

```
