### ISSUE TITLE
test for metrics targeting LiveView, EKG, Prometheus

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node-tests#83]
there were some issues with metrics not showing up in _LiveView_. In some cases this has to do with a change in configuration, the metric is not forwarded to `LIveViewBK` anymore. Or, in other cases, changes to the code were renaming metrics or the tracer context name and thus the metric was not routed correctly to the LiveView backend anymore.

A test for the presence of these metrics :
* a special configuration directing all tracers to a log file
* then, verify that the metrfics appear with correct names

To test the correct routing of metrics in the configuration:
* verify that flags are set: `TurnOnLogging` and `TurnOnLogMetrics`
* check minimum severity level
* verify that tracers are turned on: e.g. `TraceBlockFetchDecisions` ...
* verify that "options: mapBackends: " contains the correct routing to the LiveView backend:
```
  mapBackends:
    cardano.node.BlockFetchDecision.peers:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.ChainDB.metrics:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - EKGViewBK  
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.Forge.metrics:
      - EKGViewBK
```
(the `EKGViewBK` is for EKG and Prometheus)
